theme: jekyll-theme-minimal
title: Curriculum vitae
description: Martin Rajnoha - scientist, researcher and developer. My area is AI/ML in general, but primary expertise is image processing. Currently, I am working as a scientific developer dealing with creation and integration scientific methods into production.
